In [2]:
import csv
import numpy as np

# Merge the dataset into one and add an indicator to show if it is red or white wine
red_file = 'winequality-red.csv'
white_file = 'winequality-white.csv'
output_file = 'winequality-modified.csv'

final_data = []
# read the data file
for file in (red_file, white_file):
    with open(file, mode='r', newline='') as infile:
        reader = csv.reader(infile, delimiter=';')
        rows = list(reader)

    header = rows[0]
    header.insert(-1, 'red')

    is_red = 1 if file==red_file else 0

    for row in rows[1:]:
        row.insert(-1, is_red)

    # only include one header row
    if is_red == 1:
        final_data.extend(rows)
    else:
        final_data.extend(rows[1:])

In [9]:
headers = final_data[0]
values = final_data[1:]

In [10]:
headers

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'red',
 'quality']

In [11]:
values

[['7.4',
  '0.7',
  '0',
  '1.9',
  '0.076',
  '11',
  '34',
  '0.9978',
  '3.51',
  '0.56',
  '9.4',
  1,
  '5'],
 ['7.8',
  '0.88',
  '0',
  '2.6',
  '0.098',
  '25',
  '67',
  '0.9968',
  '3.2',
  '0.68',
  '9.8',
  1,
  '5'],
 ['7.8',
  '0.76',
  '0.04',
  '2.3',
  '0.092',
  '15',
  '54',
  '0.997',
  '3.26',
  '0.65',
  '9.8',
  1,
  '5'],
 ['11.2',
  '0.28',
  '0.56',
  '1.9',
  '0.075',
  '17',
  '60',
  '0.998',
  '3.16',
  '0.58',
  '9.8',
  1,
  '6'],
 ['7.4',
  '0.7',
  '0',
  '1.9',
  '0.076',
  '11',
  '34',
  '0.9978',
  '3.51',
  '0.56',
  '9.4',
  1,
  '5'],
 ['7.4',
  '0.66',
  '0',
  '1.8',
  '0.075',
  '13',
  '40',
  '0.9978',
  '3.51',
  '0.56',
  '9.4',
  1,
  '5'],
 ['7.9',
  '0.6',
  '0.06',
  '1.6',
  '0.069',
  '15',
  '59',
  '0.9964',
  '3.3',
  '0.46',
  '9.4',
  1,
  '5'],
 ['7.3',
  '0.65',
  '0',
  '1.2',
  '0.065',
  '15',
  '21',
  '0.9946',
  '3.39',
  '0.47',
  '10',
  1,
  '7'],
 ['7.8',
  '0.58',
  '0.02',
  '2',
  '0.073',
  '9',
  '18',
  '0.9968',
  '3.36',
  '0.57',
  '9.5',
  1,
  '7'],
 ['7.5',
  '0.5',
  '0.36',
  '6.1',
  '0.071',
  '17',
  '102',
  '0.9978',
  '3.35',
  '0.8',
  '10.5',
  1,
  '5'],
 ['6.7',
  '0.58',
  '0.08',
  '1.8',
  '0.097',
  '15',
  '65',
  '0.9959',
  '3.28',
  '0.54',
  '9.2',
  1,
  '5'],
 ['7.5',
  '0.5',
  '0.36',
  '6.1',
  '0.071',
  '17',
  '102',
  '0.9978',
  '3.35',
  '0.8',
  '10.5',
  1,
  '5'],
 ['5.6',
  '0.615',
  '0',
  '1.6',
  '0.089',
  '16',
  '59',
  '0.9943',
  '3.58',
  '0.52',
  '9.9',
  1,
  '5'],
 ['7.8',
  '0.61',
  '0.29',
  '1.6',
  '0.114',
  '9',
  '29',
  '0.9974',
  '3.26',
  '1.56',
  '9.1',
  1,
  '5'],
 ['8.9',
  '0.62',
  '0.18',
  '3.8',
  '0.176',
  '52',
  '145',
  '0.9986',
  '3.16',
  '0.88',
  '9.2',
  1,
  '5'],
 ['8.9',
  '0.62',
  '0.19',
  '3.9',
  '0.17',
  '51',
  '148',
  '0.9986',
  '3.17',
  '0.93',
  '9.2',
  1,
  '5'],
 ['8.5',
  '0.28',
  '0.56',
  '1.8',
  '0.092',
  '35',
  '103',
  '0.9969',
  '3.3',
  '0.75',
  '10.5',
  1,
  '7'],
 ['8.1',
  '0.56',
  '0.28',
  '1.7',
  '0.368',
  '16',
  '56',
  '0.9968',
  '3.11',
  '1.28',
  '9.3',
  1,
  '5'],
 ['7.4',
  '0.59',
  '0.08',
  '4.4',
  '0.086',
  '6',
  '29',
  '0.9974',
  '3.38',
  '0.5',
  '9',
  1,
  '4'],
 ['7.9',
  '0.32',
  '0.51',
  '1.8',
  '0.341',
  '17',
  '56',
  '0.9969',
  '3.04',
  '1.08',
  '9.2',
  1,
  '6'],
 ['8.9',
  '0.22',
  '0.48',
  '1.8',
  '0.077',
  '29',
  '60',
  '0.9968',
  '3.39',
  '0.53',
  '9.4',
  1,
  '6'],
 ['7.6',
  '0.39',
  '0.31',
  '2.3',
  '0.082',
  '23',
  '71',
  '0.9982',
  '3.52',
  '0.65',
  '9.7',
  1,
  '5'],
 ['7.9',
  '0.43',
  '0.21',
  '1.6',
  '0.106',
  '10',
  '37',
  '0.9966',
  '3.17',
  '0.91',
  '9.5',
  1,
  '5'],
 ['8.5',
  '0.49',
  '0.11',
  '2.3',
  '0.084',
  '9',
  '67',
  '0.9968',
  '3.17',
  '0.53',
  '9.4',
  1,
  '5'],
 ['6.9',
  '0.4',
  '0.14',
  '2.4',
  '0.085',
  '21',
  '40',
  '0.9968',
  '3.43',
  '0.63',
  '9.7',
  1,
  '6'],
 ['6.3',
  '0.39',
  '0.16',
  '1.4',
  '0.08',
  '11',
  '23',
  '0.9955',
  '3.34',
  '0.56',
  '9.3',
  1,
  '5'],
 ['7.6',
  '0.41',
  '0.24',
  '1.8',
  '0.08',
  '4',
  '11',
  '0.9962',
  '3.28',
  '0.59',
  '9.5',
  1,
  '5'],
 ['7.9',
  '0.43',
  '0.21',
  '1.6',
  '0.106',
  '10',
  '37',
  '0.9966',
  '3.17',
  '0.91',
  '9.5',
  1,
  '5'],
 ['7.1',
  '0.71',
  '0',
  '1.9',
  '0.08',
  '14',
  '35',
  '0.9972',
  '3.47',
  '0.55',
  '9.4',
  1,
  '5'],
 ['7.8',
  '0.645',
  '0',
  '2',
  '0.082',
  '8',
  '16',
  '0.9964',
  '3.38',
  '0.59',
  '9.8',
  1,
  '6'],
 ['6.7',
  '0.675',
  '0.07',
  '2.4',
  '0.089',
  '17',
  '82',
  '0.9958',
  '3.35',
  '0.54',
  '10.1',
  1,
  '5'],
 ['6.9',
  '0.685',
  '0',
  '2.5',
  '0.105',
  '22',
  '37',
  '0.9966',
  '3.46',
  '0.57',
  '10.6',
  1,
  '6'],
 ['8.3',
  '0.655',
  '0.12',
  '2.3',
  '0.083',
  '15',
  '113',
  '0.9966',
  '3.17',
  '0.66',
  '9.8',
  1,
  '5'],
 ['6.9',
  '0.605',
  '0.12',
  '10.7',
  '0.073',
  '40',
  '83',
  '0.9993',
  '3.45',
  '0.52',
  '9.4',
  1,
  '6'],
 ['5.2',
  '0.32',
  '0.25',
  '1.8',
  '0.103',
  '13',
  '50',
  '0.9957',
  '3.38',
  '0.55',
  '9.2',
  1,
  '5'],
 ['7.8',
  '0.645',
  '0',
  '5.5',
  '0.086',
  '5',
  '18',
  '0.9986',
  '3.4',
  '0.55',
  '9.6',
  1,
  '6'],
 ['7.8',
  '0.6',
  '0.14',
  '2.4',
  '0.086',
  '3',
  '15',
  '0.9975',
  '3.42',
  '0.6',
  '10.8',
  1,
  '6'],
 ['8.1',
  '0.38',
  '0.28',
  '2.1',
  '0.066',
  '13',
  '30',
  '0.9968',
  '3.23',
  '0.73',
  '9.7',
  1,
  '7'],
 ['5.7',
  '1.13',
  '0.09',
  '1.5',
  '0.172',
  '7',
  '19',
  '0.994',
  '3.5',
  '0.48',
  '9.8',
  1,
  '4'],
 ['7.3',
  '0.45',
  '0.36',
  '5.9',
  '0.074',
  '12',
  '87',
  '0.9978',
  '3.33',
  '0.83',
  '10.5',
  1,
  '5'],
 ['7.3',
  '0.45',
  '0.36',
  '5.9',
  '0.074',
  '12',
  '87',
  '0.9978',
  '3.33',
  '0.83',
  '10.5',
  1,
  '5'],
 ['8.8',
  '0.61',
  '0.3',
  '2.8',
  '0.088',
  '17',
  '46',
  '0.9976',
  '3.26',
  '0.51',
  '9.3',
  1,
  '4'],
 ['7.5',
  '0.49',
  '0.2',
  '2.6',
  '0.332',
  '8',
  '14',
  '0.9968',
  '3.21',
  '0.9',
  '10.5',
  1,
  '6'],
 ['8.1',
  '0.66',
  '0.22',
  '2.2',
  '0.069',
  '9',
  '23',
  '0.9968',
  '3.3',
  '1.2',
  '10.3',
  1,
  '5'],
 ['6.8',
  '0.67',
  '0.02',
  '1.8',
  '0.05',
  '5',
  '11',
  '0.9962',
  '3.48',
  '0.52',
  '9.5',
  1,
  '5'],
 ['4.6',
  '0.52',
  '0.15',
  '2.1',
  '0.054',
  '8',
  '65',
  '0.9934',
  '3.9',
  '0.56',
  '13.1',
  1,
  '4'],
 ['7.7',
  '0.935',
  '0.43',
  '2.2',
  '0.114',
  '22',
  '114',
  '0.997',
  '3.25',
  '0.73',
  '9.2',
  1,
  '5'],
 ['8.7',
  '0.29',
  '0.52',
  '1.6',
  '0.113',
  '12',
  '37',
  '0.9969',
  '3.25',
  '0.58',
  '9.5',
  1,
  '5'],
 ['6.4',
  '0.4',
  '0.23',
  '1.6',
  '0.066',
  '5',
  '12',
  '0.9958',
  '3.34',
  '0.56',
  '9.2',
  1,
  '5'],
 ['5.6',
  '0.31',
  '0.37',
  '1.4',
  '0.074',
  '12',
  '96',
  '0.9954',
  '3.32',
  '0.58',
  '9.2',
  1,
  '5'],
 ['8.8',
  '0.66',
  '0.26',
  '1.7',
  '0.074',
  '4',
  '23',
  '0.9971',
  '3.15',
  '0.74',
  '9.2',
  1,
  '5'],
 ['6.6',
  '0.52',
  '0.04',
  '2.2',
  '0.069',
  '8',
  '15',
  '0.9956',
  '3.4',
  '0.63',
  '9.4',
  1,
  '6'],
 ['6.6',
  '0.5',
  '0.04',
  '2.1',
  '0.068',
  '6',
  '14',
  '0.9955',
  '3.39',
  '0.64',
  '9.4',
  1,
  '6'],
 ['8.6',
  '0.38',
  '0.36',
  '3',
  '0.081',
  '30',
  '119',
  '0.997',
  '3.2',
  '0.56',
  '9.4',
  1,
  '5'],
 ['7.6',
  '0.51',
  '0.15',
  '2.8',
  '0.11',
  '33',
  '73',
  '0.9955',
  '3.17',
  '0.63',
  '10.2',
  1,
  '6'],
 ['7.7',
  '0.62',
  '0.04',
  '3.8',
  '0.084',
  '25',
  '45',
  '0.9978',
  '3.34',
  '0.53',
  '9.5',
  1,
  '5'],
 ['10.2',
  '0.42',
  '0.57',
  '3.4',
  '0.07',
  '4',
  '10',
  '0.9971',
  '3.04',
  '0.63',
  '9.6',
  1,
  '5'],
 ['7.5',
  '0.63',
  '0.12',
  '5.1',
  '0.111',
  '50',
  '110',
  '0.9983',
  '3.26',
  '0.77',
  '9.4',
  1,
  '5'],
 ['7.8',
  '0.59',
  '0.18',
  '2.3',
  '0.076',
  '17',
  '54',
  '0.9975',
  '3.43',
  '0.59',
  '10',
  1,
  '5'],
 ['7.3',
  '0.39',
  '0.31',
  '2.4',
  '0.074',
  '9',
  '46',
  '0.9962',
  '3.41',
  '0.54',
  '9.4',
  1,
  '6'],
 ['8.8',
  '0.4',
  '0.4',
  '2.2',
  '0.079',
  '19',
  '52',
  '0.998',
  '3.44',
  '0.64',
  '9.2',
  1,
  '5'],
 ['7.7',
  '0.69',
  '0.49',
  '1.8',
  '0.115',
  '20',
  '112',
  '0.9968',
  '3.21',
  '0.71',
  '9.3',
  1,
  '5'],
 ['7.5',
  '0.52',
  '0.16',
  '1.9',
  '0.085',
  '12',
  '35',
  '0.9968',
  '3.38',
  '0.62',
  '9.5',
  1,
  '7'],
 ['7',
  '0.735',
  '0.05',
  '2',
  '0.081',
  '13',
  '54',
  '0.9966',
  '3.39',
  '0.57',
  '9.8',
  1,
  '5'],
 ['7.2',
  '0.725',
  '0.05',
  '4.65',
  '0.086',
  '4',
  '11',
  '0.9962',
  '3.41',
  '0.39',
  '10.9',
  1,
  '5'],
 ['7.2',
  '0.725',
  '0.05',
  '4.65',
  '0.086',
  '4',
  '11',
  '0.9962',
  '3.41',
  '0.39',
  '10.9',
  1,
  '5'],
 ['7.5',
  '0.52',
  '0.11',
  '1.5',
  '0.079',
  '11',
  '39',
  '0.9968',
  '3.42',
  '0.58',
  '9.6',
  1,
  '5'],
 ['6.6',
  '0.705',
  '0.07',
  '1.6',
  '0.076',
  '6',
  '15',
  '0.9962',
  '3.44',
  '0.58',
  '10.7',
  1,
  '5'],
 ['9.3',
  '0.32',
  '0.57',
  '2',
  '0.074',
  '27',
  '65',
  '0.9969',
  '3.28',
  '0.79',
  '10.7',
  1,
  '5'],
 ['8',
  '0.705',
  '0.05',
  '1.9',
  '0.074',
  '8',
  '19',
  '0.9962',
  '3.34',
  '0.95',
  '10.5',
  1,
  '6'],
 ['7.7',
  '0.63',
  '0.08',
  '1.9',
  '0.076',
  '15',
  '27',
  '0.9967',
  '3.32',
  '0.54',
  '9.5',
  1,
  '6'],
 ['7.7',
  '0.67',
  '0.23',
  '2.1',
  '0.088',
  '17',
  '96',
  '0.9962',
  '3.32',
  '0.48',
  '9.5',
  1,
  '5'],
 ['7.7',
  '0.69',
  '0.22',
  '1.9',
  '0.084',
  '18',
  '94',
  '0.9961',
  '3.31',
  '0.48',
  '9.5',
  1,
  '5'],
 ['8.3',
  '0.675',
  '0.26',
  '2.1',
  '0.084',
  '11',
  '43',
  '0.9976',
  '3.31',
  '0.53',
  '9.2',
  1,
  '4'],
 ['9.7',
  '0.32',
  '0.54',
  '2.5',
  '0.094',
  '28',
  '83',
  '0.9984',
  '3.28',
  '0.82',
  '9.6',
  1,
  '5'],
 ['8.8',
  '0.41',
  '0.64',
  '2.2',
  '0.093',
  '9',
  '42',
  '0.9986',
  '3.54',
  '0.66',
  '10.5',
  1,
  '5'],
 ['8.8',
  '0.41',
  '0.64',
  '2.2',
  '0.093',
  '9',
  '42',
  '0.9986',
  '3.54',
  '0.66',
  '10.5',
  1,
  '5'],
 ['6.8',
  '0.785',
  '0',
  '2.4',
  '0.104',
  '14',
  '30',
  '0.9966',
  '3.52',
  '0.55',
  '10.7',
  1,
  '6'],
 ['6.7',
  '0.75',
  '0.12',
  '2',
  '0.086',
  '12',
  '80',
  '0.9958',
  '3.38',
  '0.52',
  '10.1',
  1,
  '5'],
 ['8.3',
  '0.625',
  '0.2',
  '1.5',
  '0.08',
  '27',
  '119',
  '0.9972',
  '3.16',
  '1.12',
  '9.1',
  1,
  '4'],
 ['6.2',
  '0.45',
  '0.2',
  '1.6',
  '0.069',
  '3',
  '15',
  '0.9958',
  '3.41',
  '0.56',
  '9.2',
  1,
  '5'],
 ['7.8',
  '0.43',
  '0.7',
  '1.9',
  '0.464',
  '22',
  '67',
  '0.9974',
  '3.13',
  '1.28',
  '9.4',
  1,
  '5'],
 ['7.4',
  '0.5',
  '0.47',
  '2',
  '0.086',
  '21',
  '73',
  '0.997',
  '3.36',
  '0.57',
  '9.1',
  1,
  '5'],
 ['7.3',
  '0.67',
  '0.26',
  '1.8',
  '0.401',
  '16',
  '51',
  '0.9969',
  '3.16',
  '1.14',
  '9.4',
  1,
  '5'],
 ['6.3',
  '0.3',
  '0.48',
  '1.8',
  '0.069',
  '18',
  '61',
  '0.9959',
  '3.44',
  '0.78',
  '10.3',
  1,
  '6'],
 ['6.9',
  '0.55',
  '0.15',
  '2.2',
  '0.076',
  '19',
  '40',
  '0.9961',
  '3.41',
  '0.59',
  '10.1',
  1,
  '5'],
 ['8.6',
  '0.49',
  '0.28',
  '1.9',
  '0.11',
  '20',
  '136',
  '0.9972',
  '2.93',
  '1.95',
  '9.9',
  1,
  '6'],
 ['7.7',
  '0.49',
  '0.26',
  '1.9',
  '0.062',
  '9',
  '31',
  '0.9966',
  '3.39',
  '0.64',
  '9.6',
  1,
  '5'],
 ['9.3',
  '0.39',
  '0.44',
  '2.1',
  '0.107',
  '34',
  '125',
  '0.9978',
  '3.14',
  '1.22',
  '9.5',
  1,
  '5'],
 ['7',
  '0.62',
  '0.08',
  '1.8',
  '0.076',
  '8',
  '24',
  '0.9978',
  '3.48',
  '0.53',
  '9',
  1,
  '5'],
 ['7.9',
  '0.52',
  '0.26',
  '1.9',
  '0.079',
  '42',
  '140',
  '0.9964',
  '3.23',
  '0.54',
  '9.5',
  1,
  '5'],
 ['8.6',
  '0.49',
  '0.28',
  '1.9',
  '0.11',
  '20',
  '136',
  '0.9972',
  '2.93',
  '1.95',
  '9.9',
  1,
  '6'],
 ['8.6',
  '0.49',
  '0.29',
  '2',
  '0.11',
  '19',
  '133',
  '0.9972',
  '2.93',
  '1.98',
  '9.8',
  1,
  '5'],
 ['7.7',
  '0.49',
  '0.26',
  '1.9',
  '0.062',
  '9',
  '31',
  '0.9966',
  '3.39',
  '0.64',
  '9.6',
  1,
  '5'],
 ['5',
  '1.02',
  '0.04',
  '1.4',
  '0.045',
  '41',
  '85',
  '0.9938',
  '3.75',
  '0.48',
  '10.5',
  1,
  '4'],
 ['4.7',
  '0.6',
  '0.17',
  '2.3',
  '0.058',
  '17',
  '106',
  '0.9932',
  '3.85',
  '0.6',
  '12.9',
  1,
  '6'],
 ['6.8',
  '0.775',
  '0',
  '3',
  '0.102',
  '8',
  '23',
  '0.9965',
  '3.45',
  '0.56',
  '10.7',
  1,
  '5'],
 ['7',
  '0.5',
  '0.25',
  '2',
  '0.07',
  '3',
  '22',
  '0.9963',
  '3.25',
  '0.63',
  '9.2',
  1,
  '5'],
 ['7.6',
  '0.9',
  '0.06',
  '2.5',
  '0.079',
  '5',
  '10',
  '0.9967',
  '3.39',
  '0.56',
  '9.8',
  1,
  '5'],
 ['8.1',
  '0.545',
  '0.18',
  '1.9',
  '0.08',
  '13',
  '35',
  '0.9972',
  '3.3',
  '0.59',
  '9',
  1,
  '6'],
 ['8.3',
  '0.61',
  '0.3',
  '2.1',
  '0.084',
  '11',
  '50',
  '0.9972',
  '3.4',
  '0.61',
  '10.2',
  1,
  '6'],
 ['7.8',
  '0.5',
  '0.3',
  '1.9',
  '0.075',
  '8',
  '22',
  '0.9959',
  '3.31',
  '0.56',
  '10.4',
  1,
  '6'],
 ['8.1',
  '0.545',
  '0.18',
  '1.9',
  '0.08',
  '13',
  '35',
  '0.9972',
  '3.3',
  '0.59',
  '9',
  1,
  '6'],
 ['8.1',
  '0.575',
  '0.22',
  '2.1',
  '0.077',
  '12',
  '65',
  '0.9967',
  '3.29',
  '0.51',
  '9.2',
  1,
  '5'],
 ['7.2',
  '0.49',
  '0.24',
  '2.2',
  '0.07',
  '5',
  '36',
  '0.996',
  '3.33',
  '0.48',
  '9.4',
  1,
  '5'],
 ['8.1',
  '0.575',
  '0.22',
  '2.1',
  '0.077',
  '12',
  '65',
  '0.9967',
  '3.29',
  '0.51',
  '9.2',
  1,
  '5'],
 ['7.8',
  '0.41',
  '0.68',
  '1.7',
  '0.467',
  '18',
  '69',
  '0.9973',
  '3.08',
  '1.31',
  '9.3',
  1,
  '5'],
 ['6.2',
  '0.63',
  '0.31',
  '1.7',
  '0.088',
  '15',
  '64',
  '0.9969',
  '3.46',
  '0.79',
  '9.3',
  1,
  '5'],
 ['8',
  '0.33',
  '0.53',
  '2.5',
  '0.091',
  '18',
  '80',
  '0.9976',
  '3.37',
  '0.8',
  '9.6',
  1,
  '6'],
 ['8.1',
  '0.785',
  '0.52',
  '2',
  '0.122',
  '37',
  '153',
  '0.9969',
  '3.21',
  '0.69',
  '9.3',
  1,
  '5'],
 ['7.8',
  '0.56',
  '0.19',
  '1.8',
  '0.104',
  '12',
  '47',
  '0.9964',
  '3.19',
  '0.93',
  '9.5',
  1,
  '5'],
 ['8.4',
  '0.62',
  '0.09',
  '2.2',
  '0.084',
  '11',
  '108',
  '0.9964',
  '3.15',
  '0.66',
  '9.8',
  1,
  '5'],
 ['8.4',
  '0.6',
  '0.1',
  '2.2',
  '0.085',
  '14',
  '111',
  '0.9964',
  '3.15',
  '0.66',
  '9.8',
  1,
  '5'],
 ['10.1',
  '0.31',
  '0.44',
  '2.3',
  '0.08',
  '22',
  '46',
  '0.9988',
  '3.32',
  '0.67',
  '9.7',
  1,
  '6'],
 ['7.8',
  '0.56',
  '0.19',
  '1.8',
  '0.104',
  '12',
  '47',
  '0.9964',
  '3.19',
  '0.93',
  '9.5',
  1,
  '5'],
 ['9.4',
  '0.4',
  '0.31',
  '2.2',
  '0.09',
  '13',
  '62',
  '0.9966',
  '3.07',
  '0.63',
  '10.5',
  1,
  '6'],
 ['8.3',
  '0.54',
  '0.28',
  '1.9',
  '0.077',
  '11',
  '40',
  '0.9978',
  '3.39',
  '0.61',
  '10',
  1,
  '6'],
 ['7.8',
  '0.56',
  '0.12',
  '2',
  '0.082',
  '7',
  '28',
  '0.997',
  '3.37',
  '0.5',
  '9.4',
  1,
  '6'],
 ['8.8',
  '0.55',
  '0.04',
  '2.2',
  '0.119',
  '14',
  '56',
  '0.9962',
  '3.21',
  '0.6',
  '10.9',
  1,
  '6'],
 ['7',
  '0.69',
  '0.08',
  '1.8',
  '0.097',
  '22',
  '89',
  '0.9959',
  '3.34',
  '0.54',
  '9.2',
  1,
  '6'],
 ['7.3',
  '1.07',
  '0.09',
  '1.7',
  '0.178',
  '10',
  '89',
  '0.9962',
  '3.3',
  '0.57',
  '9',
  1,
  '5'],
 ['8.8',
  '0.55',
  '0.04',
  '2.2',
  '0.119',
  '14',
  '56',
  '0.9962',
  '3.21',
  '0.6',
  '10.9',
  1,
  '6'],
 ['7.3',
  '0.695',
  '0',
  '2.5',
  '0.075',
  '3',
  '13',
  '0.998',
  '3.49',
  '0.52',
  '9.2',
  1,
  '5'],
 ['8',
  '0.71',
  '0',
  '2.6',
  '0.08',
  '11',
  '34',
  '0.9976',
  '3.44',
  '0.53',
  '9.5',
  1,
  '5'],
 ['7.8',
  '0.5',
  '0.17',
  '1.6',
  '0.082',
  '21',
  '102',
  '0.996',
  '3.39',
  '0.48',
  '9.5',
  1,
  '5'],
 ['9',
  '0.62',
  '0.04',
  '1.9',
  '0.146',
  '27',
  '90',
  '0.9984',
  '3.16',
  '0.7',
  '9.4',
  1,
  '5'],
 ['8.2',
  '1.33',
  '0',
  '1.7',
  '0.081',
  '3',
  '12',
  '0.9964',
  '3.53',
  '0.49',
  '10.9',
  1,
  '5'],
 ['8.1',
  '1.33',
  '0',
  '1.8',
  '0.082',
  '3',
  '12',
  '0.9964',
  '3.54',
  '0.48',
  '10.9',
  1,
  '5'],
 ['8',
  '0.59',
  '0.16',
  '1.8',
  '0.065',
  '3',
  '16',
  '0.9962',
  '3.42',
  '0.92',
  '10.5',
  1,
  '7'],
 ['6.1',
  '0.38',
  '0.15',
  '1.8',
  '0.072',
  '6',
  '19',
  '0.9955',
  '3.42',
  '0.57',
  '9.4',
  1,
  '5'],
 ['8',
  '0.745',
  '0.56',
  '2',
  '0.118',
  '30',
  '134',
  '0.9968',
  '3.24',
  '0.66',
  '9.4',
  1,
  '5'],
 ['5.6',
  '0.5',
  '0.09',
  '2.3',
  '0.049',
  '17',
  '99',
  '0.9937',
  '3.63',
  '0.63',
  '13',
  1,
  '5'],
 ['5.6',
  '0.5',
  '0.09',
  '2.3',
  '0.049',
  '17',
  '99',
  '0.9937',
  '3.63',
  '0.63',
  '13',
  1,
  '5'],
 ['6.6',
  '0.5',
  '0.01',
  '1.5',
  '0.06',
  '17',
  '26',
  '0.9952',
  '3.4',
  '0.58',
  '9.8',
  1,
  '6'],
 ['7.9',
  '1.04',
  '0.05',
  '2.2',
  '0.084',
  '13',
  '29',
  '0.9959',
  '3.22',
  '0.55',
  '9.9',
  1,
  '6'],
 ['8.4',
  '0.745',
  '0.11',
  '1.9',
  '0.09',
  '16',
  '63',
  '0.9965',
  '3.19',
  '0.82',
  '9.6',
  1,
  '5'],
 ['8.3',
  '0.715',
  '0.15',
  '1.8',
  '0.089',
  '10',
  '52',
  '0.9968',
  '3.23',
  '0.77',
  '9.5',
  1,
  '5'],
 ['7.2',
  '0.415',
  '0.36',
  '2',
  '0.081',
  '13',
  '45',
  '0.9972',
  '3.48',
  '0.64',
  '9.2',
  1,
  '5'],
 ['7.8',
  '0.56',
  '0.19',
  '2.1',
  '0.081',
  '15',
  '105',
  '0.9962',
  '3.33',
  '0.54',
  '9.5',
  1,
  '5'],
 ['7.8',
  '0.56',
  '0.19',
  '2',
  '0.081',
  '17',
  '108',
  '0.9962',
  '3.32',
  '0.54',
  '9.5',
  1,
  '5'],
 ['8.4',
  '0.745',
  '0.11',
  '1.9',
  '0.09',
  '16',
  '63',
  '0.9965',
  '3.19',
  '0.82',
  '9.6',
  1,
  '5'],
 ['8.3',
  '0.715',
  '0.15',
  '1.8',
  '0.089',
  '10',
  '52',
  '0.9968',
  '3.23',
  '0.77',
  '9.5',
  1,
  '5'],
 ['5.2',
  '0.34',
  '0',
  '1.8',
  '0.05',
  '27',
  '63',
  '0.9916',
  '3.68',
  '0.79',
  '14',
  1,
  '6'],
 ['6.3',
  '0.39',
  '0.08',
  '1.7',
  '0.066',
  '3',
  '20',
  '0.9954',
  '3.34',
  '0.58',
  '9.4',
  1,
  '5'],
 ['5.2',
  '0.34',
  '0',
  '1.8',
  '0.05',
  '27',
  '63',
  '0.9916',
  '3.68',
  '0.79',
  '14',
  1,
  '6'],
 ['8.1',
  '0.67',
  '0.55',
  '1.8',
  '0.117',
  '32',
  '141',
  '0.9968',
  '3.17',
  '0.62',
  '9.4',
  1,
  '5'],
 ['5.8',
  '0.68',
  '0.02',
  '1.8',
  '0.087',
  '21',
  '94',
  '0.9944',
  '3.54',
  '0.52',
  '10',
  1,
  '5'],
 ['7.6',
  '0.49',
  '0.26',
  '1.6',
  '0.236',
  '10',
  '88',
  '0.9968',
  '3.11',
  '0.8',
  '9.3',
  1,
  '5'],
 ['6.9',
  '0.49',
  '0.1',
  '2.3',
  '0.074',
  '12',
  '30',
  '0.9959',
  '3.42',
  '0.58',
  '10.2',
  1,
  '6'],
 ['8.2',
  '0.4',
  '0.44',
  '2.8',
  '0.089',
  '11',
  '43',
  '0.9975',
  '3.53',
  '0.61',
  '10.5',
  1,
  '6'],
 ['7.3',
  '0.33',
  '0.47',
  '2.1',
  '0.077',
  '5',
  '11',
  '0.9958',
  '3.33',
  '0.53',
  '10.3',
  1,
  '6'],
 ['9.2',
  '0.52',
  '1',
  '3.4',
  '0.61',
  '32',
  '69',
  '0.9996',
  '2.74',
  '2.0',
  '9.4',
  1,
  '4'],
 ['7.5',
  '0.6',
  '0.03',
  '1.8',
  '0.095',
  '25',
  '99',
  '0.995',
  '3.35',
  '0.54',
  '10.1',
  1,
  '5'],
 ['7.5',
  '0.6',
  '0.03',
  '1.8',
  '0.095',
  '25',
  '99',
  '0.995',
  '3.35',
  '0.54',
  '10.1',
  1,
  '5'],
 ['7.1',
  '0.43',
  '0.42',
  '5.5',
  '0.07',
  '29',
  '129',
  '0.9973',
  '3.42',
  '0.72',
  '10.5',
  1,
  '5'],
 ['7.1',
  '0.43',
  '0.42',
  '5.5',
  '0.071',
  '28',
  '128',
  '0.9973',
  '3.42',
  '0.71',
  '10.5',
  1,
  '5'],
 ['7.1',
  '0.43',
  '0.42',
  '5.5',
  '0.07',
  '29',
  '129',
  '0.9973',
  '3.42',
  '0.72',
  '10.5',
  1,
  '5'],
 ['7.1',
  '0.43',
  '0.42',
  '5.5',
  '0.071',
  '28',
  '128',
  '0.9973',
  '3.42',
  '0.71',
  '10.5',
  1,
  '5'],
 ['7.1',
  '0.68',
  '0',
  '2.2',
  '0.073',
  '12',
  '22',
  '0.9969',
  '3.48',
  '0.5',
  '9.3',
  1,
  '5'],
 ['6.8',
  '0.6',
  '0.18',
  '1.9',
  '0.079',
  '18',
  '86',
  '0.9968',
  '3.59',
  '0.57',
  '9.3',
  1,
  '6'],
 ['7.6',
  '0.95',
  '0.03',
  '2',
  '0.09',
  '7',
  '20',
  '0.9959',
  '3.2',
  '0.56',
  '9.6',
  1,
  '5'],
 ['7.6',
  '0.68',
  '0.02',
  '1.3',
  '0.072',
  '9',
  '20',
  '0.9965',
  '3.17',
  '1.08',
  '9.2',
  1,
  '4'],
 ['7.8',
  '0.53',
  '0.04',
  '1.7',
  '0.076',
  '17',
  '31',
  '0.9964',
  '3.33',
  '0.56',
  '10',
  1,
  '6'],
 ['7.4',
  '0.6',
  '0.26',
  '7.3',
  '0.07',
  '36',
  '121',
  '0.9982',
  '3.37',
  '0.49',
  '9.4',
  1,
  '5'],
 ['7.3',
  '0.59',
  '0.26',
  '7.2',
  '0.07',
  '35',
  '121',
  '0.9981',
  '3.37',
  '0.49',
  '9.4',
  1,
  '5'],
 ['7.8',
  '0.63',
  '0.48',
  '1.7',
  '0.1',
  '14',
  '96',
  '0.9961',
  '3.19',
  '0.62',
  '9.5',
  1,
  '5'],
 ['6.8',
  '0.64',
  '0.1',
  '2.1',
  '0.085',
  '18',
  '101',
  '0.9956',
  '3.34',
  '0.52',
  '10.2',
  1,
  '5'],
 ['7.3',
  '0.55',
  '0.03',
  '1.6',
  '0.072',
  '17',
  '42',
  '0.9956',
  '3.37',
  '0.48',
  '9',
  1,
  '4'],
 ['6.8',
  '0.63',
  '0.07',
  '2.1',
  '0.089',
  '11',
  '44',
  '0.9953',
  '3.47',
  '0.55',
  '10.4',
  1,
  '6'],
 ['7.5',
  '0.705',
  '0.24',
  '1.8',
  '0.36',
  '15',
  '63',

In [14]:
import pandas as pd
data = pd.DataFrame(values, columns=headers)

In [15]:
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,red,quality
0,7.4,0.7,0,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,1,5
1,7.8,0.88,0,2.6,0.098,25,67,0.9968,3.2,0.68,9.8,1,5
2,7.8,0.76,0.04,2.3,0.092,15,54,0.997,3.26,0.65,9.8,1,5
3,11.2,0.28,0.56,1.9,0.075,17,60,0.998,3.16,0.58,9.8,1,6
4,7.4,0.7,0,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24,92,0.99114,3.27,0.5,11.2,0,6
6493,6.6,0.32,0.36,8,0.047,57,168,0.9949,3.15,0.46,9.6,0,5
6494,6.5,0.24,0.19,1.2,0.041,30,111,0.99254,2.99,0.46,9.4,0,6
6495,5.5,0.29,0.3,1.1,0.022,20,110,0.98869,3.34,0.38,12.8,0,7
6496,6,0.21,0.38,0.8,0.02,22,98,0.98941,3.26,0.32,11.8,0,6

In [18]:
data = data.apply(pd.to_numeric)

In [19]:
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,red,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,1,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,1,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,1,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,1,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,0,6
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,0,5
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,0,6
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,0,7
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,0,6

In [20]:
summary = data.describe()

In [21]:
summary

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,red,quality
count,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000
mean,7.215307,0.339666,0.318633,5.443235,0.056034,30.525319,115.744574,0.994697,3.218501,0.531268,10.491801,0.246114,5.818378
std,1.296434,0.164636,0.145318,4.757804,0.035034,17.749400,56.521855,0.002999,0.160787,0.148806,1.192712,0.430779,0.873255
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,0.000000,3.000000
25%,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,77.000000,0.992340,3.110000,0.430000,9.500000,0.000000,5.000000
50%,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994890,3.210000,0.510000,10.300000,0.000000,6.000000
75%,7.700000,0.400000,0.390000,8.100000,0.065000,41.000000,156.000000,0.996990,3.320000,0.600000,11.300000,0.000000,6.000000
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,1.000000,9.000000

In [23]:
print(data['red'].value_counts())

red
0    4898
1    1599
Name: count, dtype: int64

In [26]:
missing = data.isnull().sum()

In [27]:
type(missing)

pandas.Series

In [29]:
data_shuffled = data.sample(frac=1, random_state=42).reset_index(drop=True)

In [30]:
data_shuffled

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,red,quality
0,7.0,0.17,0.74,12.80,0.045,24.0,126.0,0.99420,3.26,0.38,12.2,0,8
1,7.7,0.64,0.21,2.20,0.077,32.0,133.0,0.99560,3.27,0.45,9.9,1,5
2,6.8,0.39,0.34,7.40,0.020,38.0,133.0,0.99212,3.18,0.44,12.0,0,7
3,6.3,0.28,0.47,11.20,0.040,61.0,183.0,0.99592,3.12,0.51,9.5,0,6
4,7.4,0.35,0.20,13.90,0.054,63.0,229.0,0.99888,3.11,0.50,8.9,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,7.6,0.32,0.58,16.75,0.050,43.0,163.0,0.99990,3.15,0.54,9.2,0,5
6493,5.6,0.28,0.27,3.90,0.043,52.0,158.0,0.99202,3.35,0.44,10.7,0,7
6494,6.4,0.37,0.20,5.60,0.117,61.0,183.0,0.99459,3.24,0.43,9.5,0,5
6495,6.5,0.26,0.50,8.00,0.051,46.0,197.0,0.99536,3.18,0.47,9.5,0,5
6496,7.2,0.62,0.06,2.70,0.077,15.0,85.0,0.99746,3.51,0.54,9.5,1,5

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
train_data, test_data = train_test_split(data_shuffled, test_size=0.2, random_state=42)

In [ ]:
X_train = train_data.iloc[:,0:12]
y_train = train_data.iloc[:,12]
X_test = test_data.iloc[:,0:12]
y_test = test_data.iloc[:,12]

In [41]:
X_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,red
1916,7.2,0.17,0.34,6.4,0.042,16.0,111.0,0.99278,2.99,0.40,10.8,0
947,6.7,0.23,0.17,1.3,0.061,14.0,100.0,0.99250,3.07,0.55,9.5,0
877,7.9,0.16,0.30,4.8,0.037,37.0,171.0,0.99670,3.47,0.44,9.0,0
2927,7.4,0.21,0.27,1.2,0.041,27.0,99.0,0.99270,3.19,0.33,9.8,0
6063,9.9,0.54,0.26,2.0,0.111,7.0,60.0,0.99709,2.94,0.98,10.2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
3772,5.7,0.18,0.26,2.2,0.023,21.0,95.0,0.98930,3.07,0.54,12.3,0
5191,6.6,0.23,0.30,14.9,0.051,33.0,118.0,0.99835,3.04,0.54,9.0,0
5226,6.2,0.30,0.33,3.5,0.037,37.0,155.0,0.98987,3.18,0.37,12.4,0
5390,8.4,0.62,0.12,1.8,0.072,38.0,46.0,0.99504,3.38,0.89,11.8,1
860,7.4,0.36,0.33,1.4,0.025,27.0,55.0,0.99150,3.21,0.33,11.2,0